### ISSUE TITLE
Makefile.bench.include error on linux

### ISSUE THREAD

**Issue by enerc** [SACSaveCoin/BTE#6]
Hello,

Please rename bench/Example.cpp to bench/example.cpp. Its breaks the rule bench/examples.cpp in Makefile.bench.include. Linux is case sensitive :)

Thanks.

**Comment by mraksoll4** [comment]
is bug stil exist ? why you reopen issue ?

**Comment by enerc** [comment]
No ... I haven't reopened the issue
________________________________
