### ISSUE TITLE
Error with yiimp pool

### ISSUE THREAD

**Issue by wong-fi-hung** [SACSaveCoin/BTE#8]
This the logs from wallet pages:

RPC Error: error -8: label argument must be a valid label name or "*".

**Comment by mraksoll4** [comment]
it's say you address label name is invalid.

That wrong at yiimp it send wrong label name or some incorrect data to rpc.

**Comment by mraksoll4** [comment]
try this pool https://github.com/Kudaraidee/yiimp

**Comment by wong-fi-hung** [comment]
> try this pool https://github.com/Kudaraidee/yiimp

okay thanks...

**Comment by mraksoll4** [comment]
when you setup master wallet , choice only sumbit block and segwit.
next need use legacy address at pool , that can be get 

getnewaddress ( "label" "address_type" )

when you start , stratum possible say error , but you can ignore it. I tested when make GPU Update , (GPU miners for some reason have broken solo mining support - problem at tx format ) and it was work.
